version: 0.0
os: linux
files:
 - source: /Src
   destination: /home/ec2-user/python-flask-service
permissions:
  - object: /home/ec2-user/python-flask-service/app.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/python-flask-service/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  ApplicationStop:
    - location: Scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: Scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: Scripts/start_server
      runas: root
