version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
    commands:
      # Install pipenv
      - pip3 install -U Flask
      # Install all dependencies (including dependencies for running tests)
      # - pipenv install
  build:
    commands:
      # Run the unit tests
      # - pytest
      - nohup python3 hello.py &
      # Run a security check
      # - pipenv check
    
