#!/bin/bash
yum install python
sudo yum -y install python-pip
pip install virtualenv
cd /home/ec2-user/python-flask-service
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
