#!/bin/bash
sudo yum update -y
sudo yum -y upgrade
sudo yum install python37 -y
sudo yum install -y python3-pip
sudo yum -y install openssl-devel bzip2-devel libffi-devel zlib-devel sqlite sqlite-devel
cd /home/ec2-user/python-flask-service
python3 -m venv environment
source environment/bin/activate
sudo python3 -m pip install --upgrade pip
pip3 install -r requirements.txt
