#!/bin/bash
sudo yum install python37
curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
ls -a ~
export PATH=LOCAL_PATH:$PATH
source ~/PROFILE_SCRIPT
pip install virtualenv
cd /home/ec2-user/python-flask-service
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
